### PR TITLE
Microverse Project Submission - Pull Request

### PR DESCRIPTION
**Pull request by happiguru**
This is a pull request to the first Microverse project (Embedding Video and Images)

### CODE REVIEW

**Comment by peterrobert** [comment]
### PULL REQUEST UNDER REVIEW BY PETER ROBERT (TSE)

**Comment by peterrobert** [comment]
### CHANGES REQUIRED:recycle: 
**VERY IMPRESSIVE WORK :1st_place_medal: @happiguru  AND @umairarshadbutt ** 

The readme is descriptive :clap: your commit messages are perfect :clap: However there is a problem with your git-flow. You have committed your work in both the master and the feature branch. Also, you have opened your pull request from the master which is an improper use of git-flow. 
Kindly read about git-flow [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) and fix your project by creating another repo and following the git-flow guidelines
I am going to mark this project as invalid so when you fix the issue just submit another code review request.
if you have any questions kindly reach me on slack @peterrobert 

**HAPPY CODING :computer: **

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required :no_entry_sign:

The project is getting closer to approval, but there are some issues to resolve.

1. The subscribe button is not a `button` tag, it must be a button

Please implement that little change and submit another CRR.

You can find me in slack as **srodrig**, happy coding! :wave:

**Pull request merged**
